name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --build-arg REQUIREMENTS=requirements.txt --build-arg MODULES=caption,summarize,classify,embeddings --tag sillytavern-extras:$(date +%s)
